version: "3.3"

services:
  postgres:
    container_name: postgres
    image: postgres:12.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: murg
      POSTGRES_PASSWORD: tom-nook-stalks
      POSTGRES_DB: nse
    networks: 
      - stalks
  server: 
    build: ./server
    container_name: dotnet-server
    ports:
      - 5001:5001
    networks: 
      - stalks

# todo nginx client

networks: 
  stalks: